esphome:
  name: securitysense

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !? $env.esp_api_password

ota:
  password: !? $env.esp_ota_password

mqtt:
  broker: !? $env.mqtt_broker
  username: !? $env.mqtt_username
  password: !? $env.mqtt_password
  discovery: True

wifi:
  ssid: !? $env.wifi_ssid
  password: !? $env.wifi_password
  power_save_mode: none
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: SecuritySense
    password: !? $env.wifi_ap_password

binary_sensor:
  - platform: gpio
    pin: 
      number: D5
      mode:
        input: true
        pullup: true
      inverted: false
    name: "FrontDoor"
    device_class: door
  - platform: gpio
    pin: 
      number: D7
      mode:
        input: true
        pullup: true
      inverted: false
    name: "KitchenDoor"
    device_class: door
  - platform: gpio
    pin: 
      number: D1
      mode:
        input: true
        pullup: true
      inverted: false
    name: "GarageDoor"
    device_class: door
  - platform: gpio
    pin: 
      number: D6
      mode:
        input: true
        pullup: true
      inverted: false
    name: "EntrywayMotion"
    device_class: motion
  - platform: gpio
    pin: 
      number: D2
      mode:
        input: true
        pullup: false
      inverted: false
    name: "ClosetDoor"
    device_class: door

switch:
  - platform: gpio
    name: "siren"
    pin: D4
